### ISSUE TITLE
how can the project be ran ?

### ISSUE THREAD

**Issue by tomvin6** [Entonsky/GooglePhotoOrganizer#3]
i tried to use VS to open the project, but i get the message: "Could not find file 'C:\Users\tom\Desktop\GooglePhotoOrganizer\PathTreeWorker.cs'."

when trying to compile the project..
any solution for that one?
Thanks!

**Comment by Entonsky** [comment]
I've fix the problem. Try again.
Write if any issues.

**Comment by tomvin6** [comment]
Thanks.
also, I have a problem with 3 dependencies (references): 
- Google.GData.Client
- Google.GData.Extention
- Google.GData.Photos
  which versions did you used ? I will try to look for them online..

*\* edit: solved with 2.1.0.0
