### ISSUE TITLE
Invalid query [400]

### ISSUE THREAD

**Issue by ZeRoZeRoRaZ** [Entonsky/GooglePhotoOrganizer#5]
Log in attachment
[log.txt](https://github.com/Entonsky/GooglePhotoOrganizer/files/817524/log.txt)
.

**Comment by ZeRoZeRoRaZ** [comment]
I have ' in folder name and it breaks query.

**Comment by Entonsky** [comment]
Unfortunatelly Google disable support some elements of Picassa web API, which this application is based on https://developers.google.com/picasa-web/docs/3.0/releasenotes. So application currently does not work till Google create a new API.
